import type {
  ActivityEvent,
  Delivery,
  MaterialRequest,
  Project,
  ReturnRecord,
} from "./types"

export const kpis = [
  {
    label: "Solicitudes pendientes",
    value: 24,
    change: "+12%",
    trend: "up" as const,
    hint: "vs. semana anterior",
    key: "pending-requests",
  },
  {
    label: "Proyectos en curso",
    value: 18,
    change: "+3",
    trend: "up" as const,
    hint: "obras activas",
    key: "in-progress",
  },
  {
    label: "Devoluciones pendientes",
    value: 7,
    change: "-2",
    trend: "down" as const,
    hint: "en espera de revisión",
    key: "pending-returns",
  },
  {
    label: "Proyectos completados",
    value: 142,
    change: "+8%",
    trend: "up" as const,
    hint: "este trimestre",
    key: "completed",
  },
]

export const projects: Project[] = [
  {
    id: "PRJ-1042",
    name: "Parque Solar Ribera",
    client: "Helios Energía S.A.",
    location: "Monterrey, NL",
    status: "in_progress",
    engineer: "Maya Chen",
    engineerInitials: "MC",
    technicianId: "usr-tech-1",
    technician: "Carlos Ruiz (Técnico Obra)",
    priority: "high",
    createdDate: "2025-05-12",
    capacityKw: 850,
  },
  {
    id: "PRJ-1041",
    name: "Instalación Azotea Centro",
    client: "Inmuebles Meridian",
    location: "Guadalajara, JAL",
    status: "planning",
    engineer: "Javier Okoro",
    engineerInitials: "JO",
    technicianId: "usr-tech-2",
    technician: "Laura Gómez (Técnica Obra)",
    priority: "medium",
    createdDate: "2025-05-09",
    capacityKw: 320,
  },
  {
    id: "PRJ-1040",
    name: "Pergolado Solar Fase 2",
    client: "Aurora Logística",
    location: "Hermosillo, SON",
    status: "in_progress",
    engineer: "Sofía Reyes",
    engineerInitials: "SR",
    technicianId: "usr-tech-3",
    technician: "Andrés Torres (Técnico Obra)",
    priority: "urgent",
    createdDate: "2025-05-04",
    capacityKw: 1200,
  },
  {
    id: "PRJ-1039",
    name: "Red Comunitaria Lago",
    client: "BlueWave Servicios",
    location: "Puebla, PUE",
    status: "on_hold",
    engineer: "Daniel Parra",
    engineerInitials: "DP",
    technicianId: "usr-tech-1",
    technician: "Carlos Ruiz (Técnico Obra)",
    priority: "low",
    createdDate: "2025-04-28",
    capacityKw: 540,
  },
  {
    id: "PRJ-1038",
    name: "Solar Bodega Puerto",
    client: "Fletes Pacífico",
    location: "Manzanillo, COL",
    status: "completed",
    engineer: "Maya Chen",
    engineerInitials: "MC",
    technicianId: "usr-tech-2",
    technician: "Laura Gómez (Técnica Obra)",
    priority: "medium",
    createdDate: "2025-04-15",
    capacityKw: 760,
  },
  {
    id: "PRJ-1037",
    name: "Conjunto Residencial Amanecer",
    client: "Casas Vista",
    location: "Tijuana, BC",
    status: "in_progress",
    engineer: "Priya Nair",
    engineerInitials: "PN",
    technicianId: "usr-tech-3",
    technician: "Andrés Torres (Técnico Obra)",
    priority: "high",
    createdDate: "2025-04-10",
    capacityKw: 210,
  },
  {
    id: "PRJ-1036",
    name: "Cubierta Plaza Norte",
    client: "Crestline Retail",
    location: "Querétaro, QRO",
    status: "planning",
    engineer: "Javier Okoro",
    engineerInitials: "JO",
    technicianId: "usr-tech-1",
    technician: "Carlos Ruiz (Técnico Obra)",
    priority: "medium",
    createdDate: "2025-04-02",
    capacityKw: 980,
  },
  {
    id: "PRJ-1035",
    name: "Microrred Granja Valle",
    client: "Cosecha AgroTech",
    location: "Culiacán, SIN",
    status: "completed",
    engineer: "Sofía Reyes",
    engineerInitials: "SR",
    technicianId: "usr-tech-2",
    technician: "Laura Gómez (Técnica Obra)",
    priority: "low",
    createdDate: "2025-03-21",
    capacityKw: 430,
  },
]

export const materialRequests: MaterialRequest[] = [
  {
    id: "1",
    reference: "SOL-5821",
    project: "Parque Solar Ribera",
    requestedBy: "Maya Chen",
    itemsCount: 14,
    status: "pending",
    priority: "high",
    date: "2025-05-18",
  },
  {
    id: "2",
    reference: "SOL-5820",
    project: "Pergolado Solar Fase 2",
    requestedBy: "Sofía Reyes",
    itemsCount: 32,
    status: "approved",
    priority: "urgent",
    date: "2025-05-17",
  },
  {
    id: "3",
    reference: "SOL-5819",
    project: "Conjunto Residencial Amanecer",
    requestedBy: "Priya Nair",
    itemsCount: 8,
    status: "fulfilled",
    priority: "medium",
    date: "2025-05-16",
  },
  {
    id: "4",
    reference: "SOL-5818",
    project: "Instalación Azotea Centro",
    requestedBy: "Javier Okoro",
    itemsCount: 21,
    status: "pending",
    priority: "medium",
    date: "2025-05-15",
  },
  {
    id: "5",
    reference: "SOL-5817",
    project: "Red Comunitaria Lago",
    requestedBy: "Daniel Parra",
    itemsCount: 5,
    status: "rejected",
    priority: "low",
    date: "2025-05-14",
  },
  {
    id: "6",
    reference: "SOL-5816",
    project: "Solar Bodega Puerto",
    requestedBy: "Maya Chen",
    itemsCount: 17,
    status: "fulfilled",
    priority: "high",
    date: "2025-05-12",
  },
]

export const deliveries: Delivery[] = [
  {
    id: "1",
    reference: "ENT-3301",
    project: "Pergolado Solar Fase 2",
    carrier: "RailFreight Express",
    status: "in_transit",
    scheduledDate: "2025-05-21",
    items: 32,
  },
  {
    id: "2",
    reference: "ENT-3300",
    project: "Parque Solar Ribera",
    carrier: "Logística Summit",
    status: "scheduled",
    scheduledDate: "2025-05-23",
    items: 14,
  },
  {
    id: "3",
    reference: "ENT-3299",
    project: "Conjunto Residencial Amanecer",
    carrier: "Mensajería Metro",
    status: "delivered",
    scheduledDate: "2025-05-16",
    items: 8,
  },
  {
    id: "4",
    reference: "ENT-3298",
    project: "Instalación Azotea Centro",
    carrier: "Logística Summit",
    status: "delayed",
    scheduledDate: "2025-05-15",
    items: 21,
  },
  {
    id: "5",
    reference: "ENT-3297",
    project: "Solar Bodega Puerto",
    carrier: "Fletes Pacífico",
    status: "delivered",
    scheduledDate: "2025-05-13",
    items: 17,
  },
]

export const returns: ReturnRecord[] = [
  {
    id: "1",
    reference: "DEV-2210",
    project: "Red Comunitaria Lago",
    reason: "Dañado en tránsito",
    status: "in_review",
    items: 3,
    date: "2025-05-17",
  },
  {
    id: "2",
    reference: "DEV-2209",
    project: "Instalación Azotea Centro",
    reason: "Material excedente",
    status: "requested",
    items: 6,
    date: "2025-05-16",
  },
  {
    id: "3",
    reference: "DEV-2208",
    project: "Solar Bodega Puerto",
    reason: "Especificación incorrecta",
    status: "received",
    items: 2,
    date: "2025-05-12",
  },
  {
    id: "4",
    reference: "DEV-2207",
    project: "Microrred Granja Valle",
    reason: "Proyecto finalizado",
    status: "closed",
    items: 4,
    date: "2025-05-08",
  },
]

export const activity: ActivityEvent[] = [
  {
    id: "1",
    type: "approval",
    title: "Solicitud SOL-5820 aprobada",
    description: "32 artículos liberados para Pergolado Solar Fase 2",
    user: "Operaciones",
    time: "hace 12 min",
  },
  {
    id: "2",
    type: "delivery",
    title: "Entrega ENT-3301 en tránsito",
    description: "Llegada estimada 21 may vía RailFreight Express",
    user: "Logística",
    time: "hace 1 hora",
  },
  {
    id: "3",
    type: "request",
    title: "Nueva solicitud SOL-5821 registrada",
    description: "Maya Chen solicitó 14 artículos para Parque Solar Ribera",
    user: "Maya Chen",
    time: "hace 3 horas",
  },
  {
    id: "4",
    type: "return",
    title: "Devolución DEV-2210 en revisión",
    description: "3 artículos reportados como dañados en tránsito",
    user: "Daniel Parra",
    time: "hace 5 horas",
  },
  {
    id: "5",
    type: "project",
    title: "Proyecto PRJ-1042 pasó a En curso",
    description: "Iniciaron los trabajos en Parque Solar Ribera",
    user: "Maya Chen",
    time: "Ayer",
  },
]
